stages:
  - deploy
  - migrate
  - grafana

variables:
  DB_HOST: postgres
  DB_PORT: 5432
  DB_NAME: clinic
  DB_USER: admin
  POSTGRES_PASSWORD: secret

deploy_services:
  stage: deploy
  image: docker:20.10
  services:
    - docker:20.10-dind
  script:
    - apk add --no-cache docker-compose
    - docker-compose up -d --build
  only:
    - main

run_migrations:
  stage: migrate
  image: postgres:13
  script:
    - for migration in migrations/*.sql; do
        psql "postgresql://$DB_USER:$POSTGRES_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME" -f "$migration";
      done
  only:
    - main

deploy_grafana_dashboard:
  stage: grafana
  image: curlimages/curl
  script:
    - |
      # Ждем запуска Grafana
      sleep 30
      curl -X POST \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer $GRAFANA_API_KEY" \
        -d @grafana/provisioning/dashboards/services.json \
        "http://grafana:3000/api/dashboards/db"
  only:
    - main