apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  isDefault: true

- name: PostgreSQL
  type: postgres
  access: proxy
  url: postgres:5432
  database: clinic
  user: admin
  password: secret
  editable: true
